foreground   #d5c6a9
background   #1c1a15
cursor       #d5c6a9

color0       #1c1a15
color8       #958a76
color1       #8F6E3B
color9       #8F6E3B
color2       #90764C
color10      #90764C
color3       #A87C49
color11      #A87C49
color4       #C17744
color12      #C17744
color5       #AA8854
color13      #AA8854
color6       #A78B5E
color14      #A78B5E
color7       #d5c6a9
color15      #d5c6a9
