# Rebind C-b to C-a

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Split panes v and b
unbind %
unbind '"'

bind v split-window -v
bind b split-window -h

# Easily source file
bind r source-file ~/.config/tmux/tmux.conf \; display "Sourced!"

# Move through panes without prefix key
bind h select-pane -R
bind l select-pane -L
bind k select-pane -U
bind j select-pane -D

# Resize panes
bind -r C-l resize-pane -R 5
bind -r C-h resize-pane -L 5
bind -r C-k resize-pane -U 5
bind -r C-j resize-pane -D 5

# Make windows and panes start from 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on # Dynamic numbering

# STYING #

# Status line
set -g status-style 'bg=#23120c fg=#fcfbe0'
set -g status-right '%e %B, %I:%M '
set -g status-position top

set -g status-left '#{?client_prefix,#[bg=#9b3915],}  #{session_name} #[default]'

setw -g window-status-current-format ' #[fg=#9b3915]#I #[fg=#2d1e19]#W #F '
setw -g window-status-current-style 'bg=#ffecd9 bold'

setw -g window-status-format ' #[fg=#633c2d]#I #[fg=#ffecd9]#W #F '

# Panes
set -g pane-border-style 'fg=#9b3915'
set -g pane-active-border-style 'fg=#3a170a'

# Messages
set -g message-style 'bg=#2d1e19 fg=#fcfbe0'

# Allow images to show in tmux
set -g allow-passthrough on
